# dockerversion: '3.1'
name: mysql_url

services:
  mySqlURL:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3307'
    volumes:
      - my-sql:/var/lib/mysql
volumes:
  my-sql:
